<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="5" hostname="LAPTOP-2EUUN60H" failures="1" tests="1" name="Test(failed)" time="0.056" errors="0" timestamp="2023-12-27T21:05:06 IST">
  <testcase classname="test.CashLoan" name="failedTest" time="0.013">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.CashLoan.failedTest(CashLoan.java:63)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- failedTest -->
  <testcase classname="test.CashLoan" name="DeskCashLoan" time="0.0">
    <ignored/>
  </testcase> <!-- DeskCashLoan -->
  <testcase classname="test.CashLoan" name="TestLogin" time="0.0">
    <ignored/>
  </testcase> <!-- TestLogin -->
  <testcase classname="test.CashLoan" name="APICashLoan" time="0.0">
    <ignored/>
  </testcase> <!-- APICashLoan -->
  <testcase classname="test.CashLoan" name="webCashLoan" time="0.0">
    <ignored/>
  </testcase> <!-- webCashLoan -->
  <testcase classname="test.CashLoan" name="mobileCashLoan" time="0.0">
    <ignored/>
  </testcase> <!-- mobileCashLoan -->
</testsuite> <!-- Test(failed) -->
